import { Expense } from '../types/expense';

export function generateInitialExpenses(): Expense[] {
  const now = new Date();
  const currentYear = now.getFullYear();
  const currentMonth = now.getMonth();
  const currentDate = now.getDate();

  const expenses: Expense[] = [
    // Current Month (Month 0, e.g. October 2026)
    {
      id: 'exp-1',
      title: 'Uber to Downtown Office',
      amount: 14.50,
      category: 'uber',
      date: new Date(currentYear, currentMonth, currentDate, 9, 15).toISOString(),
      paidBy: 'me',
      split: 'none',
      notes: 'Morning rush hour commute',
      createdAt: Date.now() - 3600000 * 3,
    },
    {
      id: 'exp-2',
      title: 'Trader Joe\'s Weekly Groceries',
      amount: 48.20,
      category: 'groceries',
      date: new Date(currentYear, currentMonth, Math.max(1, currentDate - 1), 17, 30).toISOString(),
      paidBy: 'me',
      split: 'equal',
      notes: 'Oat milk, pasta, produce for the apartment',
      createdAt: Date.now() - 3600000 * 24,
    },
    {
      id: 'exp-3',
      title: 'Cold Brew & Artisan Pastry',
      amount: 8.75,
      category: 'coffee',
      date: new Date(currentYear, currentMonth, Math.max(1, currentDate - 1), 21, 45).toISOString(),
      paidBy: 'friend',
      split: 'none',
      notes: 'Evening coffee break',
      createdAt: Date.now() - 3600000 * 28,
    },
    {
      id: 'exp-4',
      title: 'Uber Home from Dinner',
      amount: 18.25,
      category: 'uber',
      date: new Date(currentYear, currentMonth, Math.max(1, currentDate - 2), 23, 10).toISOString(),
      paidBy: 'me',
      split: 'equal',
      notes: 'Shared ride with Alex',
      createdAt: Date.now() - 3600000 * 48,
    },
    {
      id: 'exp-5',
      title: 'Bistro Lunch Bowl',
      amount: 13.40,
      category: 'dining',
      date: new Date(currentYear, currentMonth, Math.max(1, currentDate - 2), 12, 40).toISOString(),
      paidBy: 'friend',
      split: 'none',
      createdAt: Date.now() - 3600000 * 52,
    },
    {
      id: 'exp-6',
      title: 'Spotify Premium Duo',
      amount: 14.99,
      category: 'subscriptions',
      date: new Date(currentYear, currentMonth, 1, 8, 0).toISOString(),
      paidBy: 'me',
      split: 'equal',
      createdAt: Date.now() - 3600000 * 80,
    },
    {
      id: 'exp-7',
      title: 'Uber to Airport Terminal',
      amount: 32.50,
      category: 'uber',
      date: new Date(currentYear, currentMonth, Math.max(1, currentDate - 3), 15, 20).toISOString(),
      paidBy: 'me',
      split: 'equal',
      notes: 'Shared airport carpool with Alex',
      createdAt: Date.now() - 3600000 * 90,
    },
    {
      id: 'exp-8',
      title: 'Ergonomic Desk Accessories',
      amount: 42.00,
      category: 'shopping',
      date: new Date(currentYear, currentMonth, 2, 11, 0).toISOString(),
      paidBy: 'me',
      split: 'none',
      createdAt: Date.now() - 3600000 * 100,
    },
    {
      id: 'exp-9',
      title: 'Apartment Fiber Internet & Electric',
      amount: 85.00,
      category: 'housing',
      date: new Date(currentYear, currentMonth, 1, 10, 0).toISOString(),
      paidBy: 'friend',
      split: 'equal',
      notes: 'Alex paid monthly high-speed internet',
      createdAt: Date.now() - 3600000 * 120,
    },
    {
      id: 'exp-10',
      title: 'Uber to Business Meeting',
      amount: 16.75,
      category: 'uber',
      date: new Date(currentYear, currentMonth, Math.max(1, currentDate - 4), 14, 0).toISOString(),
      paidBy: 'me',
      split: 'none',
      createdAt: Date.now() - 3600000 * 140,
    },
    {
      id: 'exp-11',
      title: 'Pho Vietnamese Noodle Dinner',
      amount: 34.00,
      category: 'dining',
      date: new Date(currentYear, currentMonth, Math.max(1, currentDate - 4), 19, 30).toISOString(),
      paidBy: 'me',
      split: 'equal',
      notes: 'Friday dinner with Alex',
      createdAt: Date.now() - 3600000 * 145,
    },
    {
      id: 'exp-12',
      title: 'Weekly Supermarket Grocery Restock',
      amount: 62.50,
      category: 'groceries',
      date: new Date(currentYear, currentMonth, Math.max(1, currentDate - 5), 16, 15).toISOString(),
      paidBy: 'friend',
      split: 'equal',
      createdAt: Date.now() - 3600000 * 160,
    },
    {
      id: 'exp-13',
      title: 'Uber Ride from Weekend Show',
      amount: 22.00,
      category: 'uber',
      date: new Date(currentYear, currentMonth, Math.max(1, currentDate - 6), 23, 40).toISOString(),
      paidBy: 'me',
      split: 'equal',
      notes: 'Late night rideshare',
      createdAt: Date.now() - 3600000 * 180,
    },

    // PREVIOUS MONTH (September 2026 - Month -1)
    // Uber spend = $120.00 (Current month = $144.00 -> exact +20.0% surge!)
    {
      id: 'exp-prev-1',
      title: 'Uber to Train Station',
      amount: 25.00,
      category: 'uber',
      date: new Date(currentYear, currentMonth - 1, 28, 16, 0).toISOString(),
      paidBy: 'me',
      split: 'none',
      createdAt: Date.now() - 86400000 * 30,
    },
    {
      id: 'exp-prev-2',
      title: 'Uber from Coworking Space',
      amount: 15.00,
      category: 'uber',
      date: new Date(currentYear, currentMonth - 1, 24, 22, 30).toISOString(),
      paidBy: 'me',
      split: 'none',
      createdAt: Date.now() - 86400000 * 34,
    },
    {
      id: 'exp-prev-3',
      title: 'Uber to Grocery Mart',
      amount: 18.00,
      category: 'uber',
      date: new Date(currentYear, currentMonth - 1, 20, 14, 15).toISOString(),
      paidBy: 'me',
      split: 'equal',
      createdAt: Date.now() - 86400000 * 38,
    },
    {
      id: 'exp-prev-4',
      title: 'Uber to Weekend Event',
      amount: 22.00,
      category: 'uber',
      date: new Date(currentYear, currentMonth - 1, 15, 12, 0).toISOString(),
      paidBy: 'me',
      split: 'none',
      createdAt: Date.now() - 86400000 * 43,
    },
    {
      id: 'exp-prev-5',
      title: 'Uber to Appointment',
      amount: 20.00,
      category: 'uber',
      date: new Date(currentYear, currentMonth - 1, 10, 9, 30).toISOString(),
      paidBy: 'me',
      split: 'none',
      createdAt: Date.now() - 86400000 * 48,
    },
    {
      id: 'exp-prev-6',
      title: 'Uber Late Evening Ride',
      amount: 20.00,
      category: 'uber',
      date: new Date(currentYear, currentMonth - 1, 4, 23, 10).toISOString(),
      paidBy: 'me',
      split: 'none',
      createdAt: Date.now() - 86400000 * 54,
    },
    {
      id: 'exp-prev-7',
      title: 'Supermarket Groceries',
      amount: 215.00,
      category: 'groceries',
      date: new Date(currentYear, currentMonth - 1, 12, 17, 0).toISOString(),
      paidBy: 'friend',
      split: 'equal',
      createdAt: Date.now() - 86400000 * 45,
    },
    {
      id: 'exp-prev-8',
      title: 'Dining Out & Takeout',
      amount: 165.00,
      category: 'dining',
      date: new Date(currentYear, currentMonth - 1, 18, 20, 0).toISOString(),
      paidBy: 'me',
      split: 'equal',
      createdAt: Date.now() - 86400000 * 40,
    },
    {
      id: 'exp-prev-9',
      title: 'Housing Utilities',
      amount: 82.00,
      category: 'housing',
      date: new Date(currentYear, currentMonth - 1, 1, 10, 0).toISOString(),
      paidBy: 'friend',
      split: 'equal',
      createdAt: Date.now() - 86400000 * 57,
    },
    {
      id: 'exp-prev-10',
      title: 'Streaming & Software Services',
      amount: 24.99,
      category: 'subscriptions',
      date: new Date(currentYear, currentMonth - 1, 1, 8, 0).toISOString(),
      paidBy: 'me',
      split: 'none',
      createdAt: Date.now() - 86400000 * 58,
    },
    {
      id: 'exp-prev-11',
      title: 'Specialty Coffee Roasters',
      amount: 38.50,
      category: 'coffee',
      date: new Date(currentYear, currentMonth - 1, 16, 15, 0).toISOString(),
      paidBy: 'me',
      split: 'none',
      createdAt: Date.now() - 86400000 * 42,
    },

    // 2 MONTHS AGO (August 2026 - Month -2)
    {
      id: 'exp-m2-1',
      title: 'Uber to Office',
      amount: 28.00,
      category: 'uber',
      date: new Date(currentYear, currentMonth - 2, 26, 8, 30).toISOString(),
      paidBy: 'me',
      split: 'none',
      createdAt: Date.now() - 86400000 * 70,
    },
    {
      id: 'exp-m2-2',
      title: 'Uber to Shopping District',
      amount: 19.50,
      category: 'uber',
      date: new Date(currentYear, currentMonth - 2, 19, 14, 0).toISOString(),
      paidBy: 'me',
      split: 'equal',
      createdAt: Date.now() - 86400000 * 77,
    },
    {
      id: 'exp-m2-3',
      title: 'Uber from Airport',
      amount: 35.00,
      category: 'uber',
      date: new Date(currentYear, currentMonth - 2, 12, 21, 30).toISOString(),
      paidBy: 'me',
      split: 'equal',
      createdAt: Date.now() - 86400000 * 84,
    },
    {
      id: 'exp-m2-4',
      title: 'Uber Evening Carpool',
      amount: 18.00,
      category: 'uber',
      date: new Date(currentYear, currentMonth - 2, 5, 23, 0).toISOString(),
      paidBy: 'me',
      split: 'none',
      createdAt: Date.now() - 86400000 * 91,
    },
    {
      id: 'exp-m2-5',
      title: 'Costco Wholesale Bulk Trip',
      amount: 198.50,
      category: 'groceries',
      date: new Date(currentYear, currentMonth - 2, 15, 16, 0).toISOString(),
      paidBy: 'friend',
      split: 'equal',
      createdAt: Date.now() - 86400000 * 81,
    },
    {
      id: 'exp-m2-6',
      title: 'Korean BBQ Dinner',
      amount: 54.00,
      category: 'dining',
      date: new Date(currentYear, currentMonth - 2, 22, 19, 45).toISOString(),
      paidBy: 'me',
      split: 'equal',
      createdAt: Date.now() - 86400000 * 74,
    },
    {
      id: 'exp-m2-7',
      title: 'Apartment Maintenance Supplies',
      amount: 45.00,
      category: 'housing',
      date: new Date(currentYear, currentMonth - 2, 2, 11, 30).toISOString(),
      paidBy: 'friend',
      split: 'equal',
      createdAt: Date.now() - 86400000 * 94,
    },

    // LAST 3RD MONTH (July 2026 - Month -3)
    {
      id: 'exp-m3-1',
      title: 'Uber to Independence Day Fireworks',
      amount: 24.50,
      category: 'uber',
      date: new Date(currentYear, currentMonth - 3, 4, 22, 15).toISOString(),
      paidBy: 'me',
      split: 'equal',
      createdAt: Date.now() - 86400000 * 120,
    },
    {
      id: 'exp-m3-2',
      title: 'Uber to City Hall',
      amount: 16.00,
      category: 'uber',
      date: new Date(currentYear, currentMonth - 3, 14, 8, 45).toISOString(),
      paidBy: 'me',
      split: 'none',
      createdAt: Date.now() - 86400000 * 110,
    },
    {
      id: 'exp-m3-3',
      title: 'Uber from Summer Concert',
      amount: 28.50,
      category: 'uber',
      date: new Date(currentYear, currentMonth - 3, 25, 23, 10).toISOString(),
      paidBy: 'me',
      split: 'equal',
      createdAt: Date.now() - 86400000 * 99,
    },
    {
      id: 'exp-m3-4',
      title: 'Uber to Hardware Store',
      amount: 14.00,
      category: 'uber',
      date: new Date(currentYear, currentMonth - 3, 29, 13, 20).toISOString(),
      paidBy: 'me',
      split: 'none',
      createdAt: Date.now() - 86400000 * 95,
    },
    {
      id: 'exp-m3-5',
      title: 'Supermarket Groceries',
      amount: 184.20,
      category: 'groceries',
      date: new Date(currentYear, currentMonth - 3, 10, 16, 30).toISOString(),
      paidBy: 'friend',
      split: 'equal',
      createdAt: Date.now() - 86400000 * 114,
    },
    {
      id: 'exp-m3-6',
      title: 'Taco Tuesday Dinner',
      amount: 28.00,
      category: 'dining',
      date: new Date(currentYear, currentMonth - 3, 16, 18, 0).toISOString(),
      paidBy: 'me',
      split: 'equal',
      createdAt: Date.now() - 86400000 * 108,
    },
    {
      id: 'exp-m3-7',
      title: 'Summer Housing Utilities & AC',
      amount: 94.00,
      category: 'housing',
      date: new Date(currentYear, currentMonth - 3, 1, 9, 0).toISOString(),
      paidBy: 'friend',
      split: 'equal',
      createdAt: Date.now() - 86400000 * 123,
    },
  ];

  return expenses;
}
